#!/usr/bin/env bash

ACTION=""

### check if git has been initialized

set_remote() {
	URL="$(git remote get-url origin)"
	PATTERN="^https?:\/\/ghp_\w+@github\.com\/.+$"
	if [[ $URL =~ $PATTERN ]]; then
		echo "It's already tokenized"
	elif [[ $URL =~ "gitlab" ]]; then
		echo "It's freakin gitlab, it's different"
	else
		token="$(awk -F'=' '/TOKEN=/{print $2}' ~/.gitcreds)"
		match="github"
		new_url="${URL%%${match}*}$token@${match}${URL##*${match}}"
		git remote set-url origin $new_url
		echo "set url to $new_url"
	fi
}

set_identity() {
	NAME="$(awk -F'=' '/NAME=/{print $2}' ~/.gitcreds)"
	EMAIL="$(awk -F'=' '/EMAIL=/{print $2}' ~/.gitcreds)"
	git name $NAME
	git email $EMAIL
	echo "set identity"
}

while getopts ":a:i" opt; do
	case $opt in
		a)
			ACTION="a"
			;;
		i)
			ACTION="i"
			;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			exit 1
			;;
	esac
done

if [ "$ACTION" = "a" ]; then
	set_identity
	set_remote
fi

if [ "$ACTION" = "i" ]; then
	set_identity
fi

# Default action when no options are provided (only set_remote)
if [ -z "$ACTION" ]; then
	set_remote
fi

# vim: ts=2 sts=2 sw=2
