#!/usr/bin/env bash

set_remote() {
	URL="$(git remote get-url origin)"
	PATTERN="^https?:\/\/ghp_\w+@github\.com\/.+$"
	if [[ $URL =~ $PATTERN ]]; then
		echo "It's already tokenized"
	elif [[ $URL =~ "gitlab" ]]; then
		echo "It's freakin gitlab, it's different"
	else
		token="$(awk -F'=' '/TOKEN=/{print $2}' ~/.gitcreds)"
		match="github"
		new_url="${URL%%${match}*}$token@${match}${URL##*${match}}"
		git remote set-url origin $new_url
		echo "set url to $new_url"
	fi
}

set_identity() {
	NAME="$(awk -F'=' '/NAME=/{print $2}' ~/.gitcreds)"
	EMAIL="$(awk -F'=' '/EMAIL=/{print $2}' ~/.gitcreds)"
	git name $NAME
	git email $EMAIL
	echo "set identity"
}

if [ "$1" = "-a" ]; then
	set_identity
	set_remote
elif [ "$1" = "-i" ]; then
	set_identity
else
	set_remote
fi

# vim: ts=2 sts=2 sw=2
