#!/usr/bin/env bash

# Define your terminal and editor
terminal="st"
editor="vim"

# Define your list of config files
declare -A config_files
config_files=(
  ["vimrc"]="$HOME/.vim/vimrc"
  ["gitconfig"]="$HOME/.gitconfig"
  ["bashrc"]="$HOME/.bashrc"
  # add more files here as needed
)

# Use dmenu to select a file
selected_file=$(printf "%s\n" "${!config_files[@]}" | dmenu -i)

# Check if script is running from a terminal
if [ -t 0 ]; then
  # If it's running from a terminal, open the selected file in the current terminal
  [[ -n $selected_file ]] && $editor "${config_files[$selected_file]}"
else
  # If it's not running from a terminal, open the selected file in a new terminal window
  [[ -n $selected_file ]] && $terminal -e $editor "${config_files[$selected_file]}"
fi
