#!/usr/bin/env bash

if [ ! -f "config.def.h" ]; then
	echo "Error: config.def.h not found. This may not be a Suckless program."
	exit 1
fi

if [ ! -f "Makefile" ]; then
	echo "Error: Makefile not found in current directory."
	exit 1
fi

if git remote get-url upstream &> /dev/null; then
	echo "Branch upstream url exists."
	exit 1
fi

read -p "program name: " name

git remote add upstream git://git.suckless.org/$name
