#!/usr/bin/env bash

branch=${1:-upstream/master}

if [ ! -f "config.def.h" ]; then
  echo "Error: config.def.h not found. This may not be a Suckless program."
  exit 1
fi

if [ ! -f "Makefile" ]; then
	echo "Error: Makefile not found in current directory."
	exit 1
fi

git rev-parse --verify --quiet $branch
if [ $? -ne 0 ]; then
	echo "Error: Branch $branch does not exist."
	exit 1
fi

make clean && rm -f config.h && git reset --hard $branch

