#!/usr/bin/env bash

if [ ! -f "config.def.h" ]; then
  echo "Error: config.def.h not found. This may not be a Suckless program."
  exit 1
fi

if [ ! -f "Makefile" ]; then
  echo "Error: Makefile not found in current directory."
  exit 1
fi

current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" != "master" ]; then
  echo "Error: Current branch is not master."
  exit 1
fi

make && sudo make install
